name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest # Hoặc windows-latest nếu bạn muốn chạy trên Windows

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Cài đặt các thư viện Python mà bạn đã liệt kê
        pip install pytest pytest-playwright pytest-allure-adaptor # Thêm allure-pytest nếu bạn muốn Allure
        pip install pytest-html pytest-xdist # Các thư viện khác bạn dùng
        # Nếu bạn có file requirements.txt, hãy sử dụng: pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: playwright install --with-deps

    - name: Run Pytest tests
      run: pytest tests/ -v -s --alluredir=allure-results

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install default-jre # Allure cần Java
        wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz # Thay đổi version nếu cần
        tar -xf allure-2.29.0.tgz -C /opt/
        sudo ln -s /opt/allure-2.29.0/bin/allure /usr/local/bin/allure

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }} 
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30